update .local/functions

diff --git a/.local/functions b/.local/functions
--- a/.local/functions
+++ b/.local/functions
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 pd() {
-{    case "${1}" in
+{    case "$1" in
         -[0-9]) popd +"${1//[!0-9]/}" || return ;;
         +[0-9]) pushd "$1" || return ;;
         -c) dirs -c ;;
@@ -14,28 +14,27 @@ dirs -v
 
 extract() {
     case "$1" in
-        *.tar.bz2)   tar xjf "$1"      ;;
-        *.tar.gz)    tar xzf "$1"      ;;
-        *.bz2)       bunzip2 "$1"      ;;
-        *.rar)       rar x "$1"        ;;
-        *.gz)        gunzip "$1"       ;;
-        *.tar)       tar xf "$1"       ;;
-        *.tbz2)      tar xjf "$1"      ;;
-        *.tgz)       tar xzf "$1"      ;;
-        *.zip)       unzip "$1"        ;;
-        *.Z)         uncompress "$1"   ;;
-        *.7z)        7z x "$1"         ;;
-        *)           printf "%s cannot be extracted" "$1" ;;
+        *.tar.bz2) tar xjf "$1" ;;
+        *.tar.gz) tar xzf "$1" ;;
+        *.bz2) bunzip2 "$1" ;;
+        *.rar) rar x "$1" ;;
+        *.gz) gunzip "$1" ;;
+        *.tar) tar xf "$1" ;;
+        *.tbz2) tar xjf "$1" ;;
+        *.tgz) tar xzf "$1" ;;
+        *.zip) unzip "$1" ;;
+        *.Z) uncompress "$1" ;;
+        *.7z) 7z x "$1" ;;
+        *) printf "%s cannot be extracted" "$1" ;;
     esac
 }
 
 checkmounts() {
-mountpoints=($(awk '$1 !~ /^#/ && $2 ~ /^[/]/ {print $2}' /etc/fstab))
-for mount in "${mountpoints[@]}"; do
-   if ! findmnt "$mount" &> /dev/null; then
-      printf "%s is declared in fstab but not mounted\n" "$mount"
-   else
-      printf "$mount is mounted properly\n" "$mount"
-   fi
-done
+    while IFS="" read -r mount; do
+        if ! findmnt "$mount" &> /dev/null; then
+            printf "%s is declared in fstab but not mounted\n" "$mount"
+        else
+            printf "%s is mounted properly\n" "$mount"
+        fi
+    done < <(awk '$1 !~ /^#/ && $2 ~ /^[/]/ {print $2}' /etc/fstab)
 }
